name: Mirror to Team Repository b/public/scripts/

on:
  push:
    branches: [ main ]

jobs:
  mirror:
    if: github.repository != 'SketchShifter/sketchshifter_compiler'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository (a)
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # 履歴は不要
          persist-credentials: false

      - name: Clone destination repository (b)
        run: |
          git clone https://${{ secrets.PERSONAL_TOKEN }}@github.com/SketchShifter/sketchshifter_compiler.git destination
          rm -rf destination/public/scripts/*
          cp -r . destination/public/scripts/
          cd destination

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add public/scripts
          git commit -m "Mirror from repo a on $(date)" || echo "No changes to commit"
          git push origin main
